[package]
name = "rpi-power"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
